baseURL: https://mikailintech.github.io/

languageCode: en-us
title: "Mikail's portfolio"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # set background image
  background: "images/background3.gif"

  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/MikailINTech/mikail.github.io
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify whether you want the language flags to be displayed. 
  showFlags: true

  # specify whether you can use emojis
  enableEmoji: true

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

  darkMode:
    enable: true
    provider: darkreader
    default: dark

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true

    analytics:
      enabled: true
      goatCounter:
        code: mikail
        
  newsletter:
      enable: false